In [1]:
import numpy as np
import matplotlib.pyplot as plt


b=0.1 # taxa média de contatos 
sig = 0.01 # desvio da taxa de contatos 
shape = b**2/sig**2 # parametro de forma da gamma
scale = sig**2/b # parametro de escala da gamma
ate=600 # tempo de simulação
v = 1/14 # taxa média de contatos 
cv = v**2*9 
# parametros da distribuição beta 
abeta = (v/cv)*(1/v-cv-1) 
bbeta = abeta*(1/v-1)
N=3.885*10**6 # população 



In [2]:
#%matplotlib
num=10000 # numero de simulações 
# requisição de memória
se = N*np.ones([num,ate]) # suscetiveis
ie = np.zeros([num,ate]) # infectados
be = np.zeros([num,ate]) # salvar as amostras da distribuição
ve = np.zeros([num,ate]) # salvar as amostras da distribuição
hme = np.zeros([num,ate]) # novos infectados

for k in range(0,num):
    ie[k][0] = 20 # condição inicial
    se[k][0] =  N-ie[k][0] # condição inicial
    for t in range(1,ate):
        be[k][t] = np.random.gamma(shape,scale) # instância da gamma 
        ve[k][t] = np.random.beta(abeta,bbeta) # instância da gamma 
        hme[k][t]=be[k][t]*se[k][t-1]*ie[k][t-1]/N # novos casos
        se[k][t]=se[k][t-1]-hme[k][t] # fluxo dos suscetíveis 
        ie[k][t]=(1-ve[k][t])*ie[k][t-1]+hme[k][t] # fluxo dos infectados


In [3]:
# padrão de plotagem dos gráficos
def plotfilt(x,y,ax):
    ax.plot(x,y.mean(axis=0),'b',linewidth=1.0)
    al = [0.5, 0.75, 0.75, 0.5] # niveis de transparência
    quan = [0.05,0.5,0.95,1] # seperação em quantis 5% 50% 95% 100% dos dados
    ya = np.quantile(y, 0, axis=0)
    for k in range(1,5):
        yp = np.quantile(y, quan[k-1], axis=0)
        ax.fill_between(x,ya,yp, alpha=al[k-1],color='black')
        ya[:] = yp[:]
    

In [4]:
%matplotlib # para abrir em janela separada

Using matplotlib backend: Qt5Agg


In [5]:

fig= plt.figure(2)
posi=378 # instatne que é mostrado o histograma


In [6]:

ax = fig.add_subplot(2,2,1)
ax.set_ylabel('Suscetíveis')
ax.set_xlabel('Tempo (dias)')
plotfilt(np.arange(0,ate),se,ax)
ax.plot([posi,posi],[se.T[posi].min(), se.T[posi].max()],'r') # região do histograma

In [7]:

ax = fig.add_subplot(2,2,2)
ax.set_ylabel('Infecados')
ax.set_xlabel('Tempo (dias)')
plotfilt(np.arange(0,ate),ie,ax)
ax.plot([posi,posi],[ie.T[posi].min(), ie.T[posi].max()],'r')# região do histograma

In [8]:
ax = fig.add_subplot(2,2,3)
ax.set_ylabel('Histograma de um instante dos suscetíveis')
ax.hist(se.T[posi][0:],50,color='red') # plota histograma
#plotfilt(np.arange(0,ate),be,ax)

(array([  3.,   1.,   6.,  13.,  13.,  21.,  25.,  33.,  41.,  67.,  99.,
        123., 140., 163., 231., 325., 337., 381., 427., 492., 507., 538.,
        582., 564., 581., 584., 549., 499., 442., 403., 371., 281., 256.,
        243., 158., 124., 118.,  81.,  55.,  40.,  31.,  17.,  18.,  10.,
          4.,   1.,   1.,   0.,   0.,   1.]),
 array([2303628.13924667, 2323298.06162637, 2342967.98400608,
        2362637.90638579, 2382307.8287655 , 2401977.75114521,
        2421647.67352492, 2441317.59590463, 2460987.51828433,
        2480657.44066404, 2500327.36304375, 2519997.28542346,
        2539667.20780317, 2559337.13018288, 2579007.05256259,
        2598676.97494229, 2618346.897322  , 2638016.81970171,
        2657686.74208142, 2677356.66446113, 2697026.58684084,
        2716696.50922054, 2736366.43160025, 2756036.35397996,
        2775706.27635967, 2795376.19873938, 2815046.12111909,
        2834716.0434988 , 2854385.9658785 , 2874055.88825821,
        2893725.81063792, 2913395.7330

In [9]:
ax = fig.add_subplot(2,2,4)
ax.set_ylabel('Histograma de um instante dos infectados')
ax.hist(ie.T[posi][0:],50,color='red')
#plotfilt(np.arange(0,ate),ve,ax)

(array([  1.,   0.,   0.,   0.,   2.,   1.,   3.,   6.,  21.,  27.,  40.,
         73., 111., 131., 180., 219., 290., 398., 454., 478., 565., 601.,
        608., 655., 717., 632., 595., 524., 492., 459., 358., 301., 238.,
        198., 165., 118., 102.,  59.,  61.,  36.,  34.,  16.,   6.,  11.,
          6.,   3.,   1.,   2.,   1.,   1.]),
 array([ 97727.70111263, 100883.61356001, 104039.5260074 , 107195.43845478,
        110351.35090216, 113507.26334954, 116663.17579692, 119819.0882443 ,
        122975.00069168, 126130.91313906, 129286.82558644, 132442.73803383,
        135598.65048121, 138754.56292859, 141910.47537597, 145066.38782335,
        148222.30027073, 151378.21271811, 154534.12516549, 157690.03761287,
        160845.95006026, 164001.86250764, 167157.77495502, 170313.6874024 ,
        173469.59984978, 176625.51229716, 179781.42474454, 182937.33719192,
        186093.2496393 , 189249.16208668, 192405.07453407, 195560.98698145,
        198716.89942883, 201872.81187621, 205028.7

In [10]:
# plota evolução do segundo momento do instante final 
sigs = np.zeros(num)
sigi = np.zeros(num)

for t in range(1,num):
    errs = (se.T[-1][t])**2 # segundo momento
    sigs[t]=sigs[t-1]+(errs-sigs[t-1])/t # média recursiva
    erri = (ie.T[-1][t])**2
    sigi[t]=sigi[t-1]+(erri-sigi[t-1])/t

# gera gráficos    
fig= plt.figure(3)
ax3=fig.add_subplot(1,2,1)
ax3.set_ylabel('Segundo momento do instante final, suscetíveis')
ax3.set_xlabel('Amostras')
ax3.plot(sigs[1:-1])
ax3=fig.add_subplot(1,2,2)
ax3.plot(sigi[1:-1])
ax3.set_ylabel('Segundo momento do instante final, infectados')
ax3.set_xlabel('Amostras')


Text(0.5, 0, 'Amostras')